### ISSUE TITLE
Don't record, intent error

### ISSUE THREAD

**Issue by vdbrink** [razzo04/rhasspy-mobile-app#13]
I tried the app, version 1.7.0
The record button don't do anything when I press it. 

Sending text message works fine. 

I run it on a Samsung s10. 

This is the exception I get:

```[D] TIME: 2021-09-11T20:21:02.150304 Starting mqtt... TAG: MQTT
[I] TIME: 2021-09-11T20:21:04.120158 Start recording TAG: APP
[I] TIME: 2021-09-11T20:21:08.855892 Stop recording TAG: APP
[E] TIME: 2021-09-11T20:21:29.190591  TAG: NoSuchMethodError: The getter 'intentName' was called on null.
Receiver: null
Tried calling: intentName
#0      _IntentViewerState.build (package:rhasspy_mobile_app/widget/Intent_viewer.dart:28)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627)
#3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4343)
#5      StatefulElement.update (package:flutter/src/widgets/framework.dart:4832)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:3314)
#7      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647)
#8      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3314)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125)
#11     Element.updateChild...... 
(package:flutter/src/scheduler/binding.dart:1117)
#141    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055)
#142    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971)
#143    _rootRun (dart:async/zone.dart:1190)
#144    _CustomZone.run (dart:async/zone.dart:1093)
#145    _CustomZone.runGuarded (dart:async/zone.dart:997)
#146    _invoke (dart:ui/hooks.dart:251)
#147    _drawFrame (dart:ui/hooks.dart:209)
```

**Comment by razzo04** [comment]
It seems like rhasspy is sending a nlu intent parsed message but without the intent field. Can you send me the rhasspy configuration so I can try to troubleshoot the problem?

**Comment by vdbrink** [comment]
tnx for the response, so it's not the app but Rhasspy! 

I had Intent Handling on disabled but what is the right setting for this?

I also read something about `rhasspy-nlu`. I'll give that a try!

This is my config:
```
{
    "dialogue": {
        "system": "rhasspy",
        "volume": "1"
    },
    "handle": {
        "system": "remote"
    },
    "intent": {
        "system": "fsticuffs"
    },
    "microphone": {
        "pyaudio": {
            "device": "1"
        },
        "system": "pyaudio"
    },
    "mqtt": {
        "enabled": "true",
        "host": "mosquitto"
    },
    "sounds": {
        "aplay": {
            "device": "sysdefault:CARD=Device",
            "volume": "0.4"
        },
        "system": "aplay"
    },
    "speech_to_text": {
        "system": "kaldi"
    },
    "text_to_speech": {
        "system": "wavenet",
        "wavenet": {
            "sample_rate": "16000",
            "voice": "nl-NL-Wavenet-A"
        }
    },
    "wake": {
        "pocketsphinx": {
            "keyphrase": "x"
        },
        "system": "pocketsphinx"
    }
}
```

**Comment by vdbrink** [comment]
It works now!

I installed extra package `apt-get install libfst-tools libngram-tools` so `fstcompile` is available.

And I removed the `?` characters from Sentences file which blocked the new training.
